removing sphinx action and testing a new approach, v2

diff --git a/.github/workflows/sphinx.yml b/.github/workflows/sphinx.yml
--- a/.github/workflows/sphinx.yml
+++ b/.github/workflows/sphinx.yml
@@ -14,17 +14,25 @@ jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v3
+    - uses: actions/checkout@v4  # Updated to use v4
+    - name: List directory contents
+      run: ls -la "$GITHUB_WORKSPACE"
     - name: Set up Python
       uses: actions/setup-python@v3
       with:
         python-version: '3.x'
     - name: Install Sphinx and dependencies
       run: pip install sphinx sphinx_markdown_builder
-    - name: Build Documentation
-      run: cd docs && make doc
+    - name: Check docs directory and Build Documentation
+      run: |
+        if [ -d "$GITHUB_WORKSPACE/docs" ]; then
+          cd "$GITHUB_WORKSPACE/docs" && ls -la && make doc
+        else
+          echo "Documentation directory not found!"
+          exit 1
+        fi
     - uses: actions/upload-artifact@v3
       with:
         name: Documentation
-        path: "docs/_build/html/"
+        path: "$GITHUB_WORKSPACE/docs/_build/html/"
 
